### ISSUE TITLE
Release Version 0.7 Checklist

### ISSUE THREAD

**Issue by goneall** [spdx/Spdx-Java-Library#34]
- [x] Update dependency versions in the pom.xml file
- [x] Update the version in the pom.xml file
- [x] Publish using the command `maven deploy` - this will deploy to the [bintray SPDX tools](https://bintray.com/spdx/spdx-tools)
- [x] Sync the bintray repo with Maven Central
- [x] Tag the repo with the release version
- [x] Publish the release on github
